Dau\DauBundle\Entity\AutoList:
  type: entity
  table: auto_list
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    title:
      type: string
      length: 150
      fixed: false
      nullable: false
    annonce:
      type: text
      nullable: false
    marca:
      type: string
      length: 100
      fixed: false
      nullable: false
    autoYear:
      type: smallint
      nullable: false
      column: auto_year
    typeFuel:
      type: integer
      unsigned: false
      nullable: false
      column: type_fuel
    capacitateCil:
      type: float
      nullable: false
      column: capacitate_cil
    cutieViteza:
      type: integer
      unsigned: false
      nullable: false
      column: cutie_viteza
    fix:
      type: string
      length: 20
      fixed: false
      nullable: false
    mobil:
      type: string
      length: 20
      fixed: false
      nullable: false
    url:
      type: string
      length: 200
      fixed: false
      nullable: false
    salonPiele:
      type: integer
      unsigned: false
      nullable: false
      column: salon_piele
    aerConditionat:
      type: integer
      unsigned: false
      nullable: false
      column: aer_conditionat
    cdMp3:
      type: integer
      unsigned: false
      nullable: false
      column: cd_mp3
    userid:
      type: integer
      unsigned: false
      nullable: false
    email:
      type: string
      length: 50
      fixed: false
      nullable: false
    price:
      type: integer
      unsigned: false
      nullable: false
    currency:
      type: string
      length: 3
      fixed: false
      nullable: false
  lifecycleCallbacks: {  }
