Dau\DauBundle\Entity\FlatStats:
  type: entity
  table: flat_stats
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    ip:
      type: string
      length: 16
      fixed: false
      nullable: false
    time:
      type: datetime
      nullable: false
    browser:
      type: string
      length: 150
      fixed: false
      nullable: false
    idFlat:
      type: integer
      unsigned: false
      nullable: false
      column: id_flat
  lifecycleCallbacks: {  }
