Dau\DauBundle\Entity\LogAtt:
  type: entity
  table: log_att
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    email:
      type: string
      length: 150
      fixed: false
      nullable: false
    pass:
      type: string
      length: 50
      fixed: false
      nullable: false
    dateAdded:
      type: datetime
      nullable: false
      column: date_added
    ip:
      type: string
      length: 17
      fixed: false
      nullable: false
    browser:
      type: string
      length: 200
      fixed: false
      nullable: false
  lifecycleCallbacks: {  }
